---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ./.yamllint
platforms:
  - name: canary
    image: centos:7
    published_ports:
      - 8080:80
provisioner:
  name: ansible
  inventory:
    host_vars:
      canary:
        ws_repo_version: add-camel-middleware
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    - lint
    - verify
verifier:
  name: testinfra
  lint:
    name: flake8
