---
# EPEL required for python-pip install
- name: "Ensure EPEL repository is installed | RHEL7"
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: "installed"
  when:
    - 'ansible_os_family == "RedHat"'
    - 'ansible_distribution_major_version == "7"'
  become: True

- name: "Ensure pip is installed"
  package:
    name: "python-pip"
    state: "latest"
  when: '(ansible_os_family == "RedHat" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "Fedora")'
  become: True

- name: "Check virtual environment exists"
  stat:
    get_attributes: False
    get_checksum: False
    get_mime: False
    path: "{{ tower_venv_path }}"
  register: "tower_venv_path_check"

- name: "Initialize virtual environment"
  include_tasks: "init_venv.yml"
  when: 'not tower_venv_path_check.stat.exists'

- name: "Ensure Python libraries are installed to virtual environment"
  pip:
    name: "{{ tower_venv_pylibs }}"
    umask: "{{ tower_venv_umask }}"
    virtualenv: "{{ tower_venv_path }}"
    virtualenv_command: "virtualenv"
    state: "latest"
  become: True
