---
discovered_host_install_prereqs: True
discovered_host_inventory_name: "Discovered Hosts"
discovered_host_inventory_description: "Inventory of hosts scanned by the Ansible Migration Factory Discovery playbook"
discovered_host_inventory_default_group:
  name: "Unknown Application"
  desc: "Hosts running applications or services that we could not identify"
# Tower connection info
tower_url: "{{ lookup('env', 'TOWER_HOST') | default('') }}"
tower_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') | default(False) }}"
tower_user: "{{ lookup('env', 'TOWER_USERNAME') | default('') }}"
tower_pass: "{{ lookup('env', 'TOWER_PASSWORD') | default('') }}"
# Tower Org to put new inventory into
tower_org: ""
# Configurable on how to name the host when adding it to the discovered hosts inventory
tower_client_node_name: "{{ inventory_hostname }}"
vars_dir: "/tmp/discovered_facts"
