---
- name: "Restart apache"
  service:
    state: "restarted"
    name: "{{ ws_apache_svc }}"
    enabled: True
  become: True

- name: "Restart postgresql"
  service:
    name: "{{ postgres_service }}"
    state: "restarted"
  become: True

- name: "Restart coalmine"
  service:
    state: "restarted"
    name: "wildfly"
    enabled: True
  become: True
