---
amf_as_services: []

amf_as_user_group:
  users: []
  groups: []

amf_as_paths: []

amf_as_packages: []

amf_as_ports: []

amf_as_processes:
  - "PkManager.py"

amf_as_scores:
  users: "0"
  groups: "1"
  services: "0"
  paths: "0"
  packages: "0"
  ports: "0"
  processes: "1"

# Returned fields
amf_as_discovered_app:
  name: "Manhattan Warehouse Management"
  desc: "Hosts identified as Manhattan Warehouse Management Servers"