---
amf_as_services: []

amf_as_user_group:
  users: []
  groups: []

amf_as_paths: []

amf_as_packages: []

amf_as_ports: []

amf_as_processes:
  - "startWebLogic.sh"
  - "startManagedWebLogic.sh"
  - "weblogic.Server"
  - "opmn"

amf_as_scores:
  users: "0"
  groups: "0"
  services: "0"
  paths: "0"
  packages: "0"
  ports: "0"
  processes: "4"

# Returned fields
amf_as_discovered_app:
  name: "Oracle Weblogic Server"
  desc: "Hosts identified as Oracle Weblogic Servers"