postgres:
  image: postgres:9.5.3
  expose:
    - 5432
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=redhat
    - POSTGRES_PASSWORD=redhat
#  volumes:
#    -  /tmp/postgresdb:/var/lib/postgresql/data

